### ISSUE TITLE
Issue 1 - User can “favorite” a team(s) from a full list of NHL teams

### ISSUE THREAD

**Issue by eacorcoran** [eacorcoran/nhl-team-info#1]
## 💰 Motivation

Users may only care about specific teams and we should make it easy for them to focus on their preferences

## 📐 Plan

Expose a list of all conferences and teams in an easy to read list in order to allow users to select a favorite(s)

## 🖼️ Wireframes

![image](https://github.com/user-attachments/assets/9231b474-1a9c-4e91-ba8c-81ba48aafdfd)
![image](https://github.com/user-attachments/assets/6222400d-577e-4b36-b6ff-531ab1d13155)

## ✅ Task List

Team Page Content:
- [x] Create the HTML for the header making sure that "teams" is underlined so that it matches the Figma
- [x] Update the HTML to have the header text for the team information so that it matches the Figma
- [x] Populate team data from API
- [x] Add code to automatically update the HTML for the table of teams based on Figma
- [x] Create the HTML for the footer so that it matches the Figma
- [x] Add season filter to the page and verify that all api data is fetched with the selected value
- [x] Add an event listener to the 'star icon' that when clicked marks the associated team as a "favorite"
- [x] When a team is marked as a "favorite", it should be stored in local storage so that it is maintained
- [x] When a team is marked as a "favorite", the original star icon should be updated to the "favorited star icon"
- [x] When a team is marked as a "favorite", it should be at the top of the list of teams in the table
- [x] Add an event listener to the "roster" link, so that when clicked it will take the user to a page that shows the roster for the selected team and season
- [x] Add an event listener to the "schedule" link, so that when clicked it will take the user to a page that shows the schedule for the selected team and season
- [x] Complete the HTML using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Add event listener to "team" link in the header, so that when the "teams" link is clicked, the user will be shown the "teams" content 
- [x] Make email subscription button functional

Polish:
- [x] Mark new teams as "favorites" then reloading the page to confirm that:
  - [x] the data model is being saved to `localStorage` after each change.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
