### ISSUE TITLE
Issue 5: Polish

### ISSUE THREAD

**Issue by eacorcoran** [eacorcoran/nhl-team-info#13]
## ✅ Task List

- [x] Update font to be Roboto for the entire project
- [x] Only show "Key Statistics" link in the "Schedule" table if the game has been completed
- [x] Add "Back to Teams" link on Roster view [Should take user back to Teams view]
- [x] Add "Back to Teams" link on Schedule view [Should take user back to Teams view]
- [x] Add "Back to Schedule" link on Key Statistics view [Should take user back to Schedule view]
- [x] Clean up styles.css
- [x] Clean up main.ts
- [x] Clean up data.ts
