### ISSUE TITLE
Issue 2 - User can remove a team from being a "favorite"

### ISSUE THREAD

**Issue by eacorcoran** [eacorcoran/nhl-team-info#2]
## 💰 Motivation

Users may only care about specific teams and we should make it easy for them to focus on their preferences

## 📐 Plan

Expose a list of all conferences and teams in an easy to read list in order to allow users to update their "favorited" teams and conferences

## 🖼️ Wireframes
![image](https://github.com/user-attachments/assets/8a89f170-43ee-4546-852b-ce8df5bc5b5e)

## ✅ Task List

Update Team Page:
- [x] Add an event listener to the 'favorited star icon' that when (after it has already been marked as a favorite) causes the modal to be shown
- [x] Format modal
- [x] Add an event listener to the "Cancel" button on the modal 
- [x] If "Cancel" is clicked, the relevant team remains as a favorite (i.e. no changes) and the modal is dismissed
- [x] Add an event listener to the "Confirm" button on the modal 
- [x] If "Confirm" is clicked, the relevant team will be removed as a "favorite"
- [x] When a team is removed as a "favorite", local storage should be updated
- [x] If "Confirm" is clicked, the 'favorited star icon' should be updated to be the original star 
- [x] If "Confirm" is clicked, then the previously favorited team will no longer appear at the top of the teams list

Polish:
- [x] Test the app by submitting some new entries and then reloading the page to confirm that:
  - [x] the data model is being saved to `localStorage` after each change.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
