### ISSUE TITLE
Issue 3 - User can see the full schedule for a selected team and season

### ISSUE THREAD

**Issue by eacorcoran** [eacorcoran/nhl-team-info#3]
## ⚙️ Feature

User can select a season and team to see the seleced team's schedule

## 🖼️ Wireframes
![image](https://github.com/user-attachments/assets/08292cec-2326-4d3b-9719-e89aa598d815)

![image](https://github.com/user-attachments/assets/4deafa15-1290-4584-a29f-2f8cf71dfa29)

## ✅ Task List

- [x] Update schedules page to have team dropdown
- [x] Update schedules page to have season dropdown
- [x] Update season header to be dynamic based on team and season selected
- [x] Update schedules link in header to take user to the schedules page
- [x] When schedules page is showing, the schedules link should be underlined in the header
- [x] When schedule link is clicked from teams page, the team dropdown should be populated correctly
- [x] When schedule link is clicked from teams page, the season dropdown should be populated based on selection
- [x] When schedule link is clicked from header, the team dropdown should default to no team selection
- [x] When schedule link is clicked from header, the season dropdown should default to what is selected on the current page.
- [x] Game column should show which game in the season the row refers to
- [x] Away Team column should have the team name above the logo
- [x] Home Team column should have the team name above the logo
- [x] Date/Time column should be formatted and show in the timezone of the venue
- [x] Venue column should show the name of the venue
- [x] Score column should show the score if the game is completed
- [x] Score column should show nothing if the game has not been completed
- [x] Links column should have a link that says "Key Statistics"
- [x] Add selected season to local storage, so that the selection is retained after refresh
- [x] Add selected team to local storatge, so that the selection is retained after a refresh
