### ISSUE TITLE
Issue 4 - User can key statistics for a specific game on a team's schedule

### ISSUE THREAD

**Issue by eacorcoran** [eacorcoran/nhl-team-info#6]
## ⚙️ Feature

Fans can see key statistics from a matchup, so they can understand how a team performed

## 🖼️ Wireframes

![image](https://github.com/user-attachments/assets/98635033-2967-4bd6-bdf2-c273ee9f31c0)

![image](https://github.com/user-attachments/assets/91871805-a56a-4f44-bfa0-100ef4e14321)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Clicking the "Key Statistics" link for a match-up takes you the "Key Statistics" view
- [x] The "Key Statistics" view has data populated from the API
- [x] In the "Key Statistics" view, the header links for both "Schedule" and "Teams" links should no longer be underlined
- [x] "Key Statistics" title should be dynamically updated with the game information
- [x] "Key Statistics" logos should be dynamically updated
- [x] "Key Statistics" should be updated/formatted:
- [x] Score
- [x] Shots on Goal
- [x] Face Off Winning %
- [x] Power Play
- [x] Penalty Infraction Minutes
- [x] Hits
- [x] Blocked Shots
- [x] Local Storage is updated so if "Key Statistics" page is refreshed, the data will show appropriately.
- [x] Page is optimized for mobile
